FROM node:14-alpine AS builder
ENV NODE_ENV production
# Add a work directory
WORKDIR /app
# Cache and Install dependencies
COPY package.json .
COPY package-lock.json .
RUN npm install -g serve
RUN npm install --production
# Copy app files
COPY . .
# Build the app
RUN npm run build

CMD ["npx", "serve", "-s", "build"]
