FROM node:19.4
#ENV NODE_ENV production
# Add a work directory
WORKDIR /app
# Cache and Install dependencies
COPY package.json .

RUN npm i -g serve
RUN npm i
# Copy app files
COPY . .

# Build the app
RUN npm run build
