FROM node:14-alpine AS builder
ENV NODE_ENV production
# Add a work directory
WORKDIR /app
# Cache and Install dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn global add -g serve
RUN yarn
# Copy app files
COPY . .
# Build the app

CMD ["yarn", "build"]
CMD ["npx", "serve", "-s", "build"]
